version: '3'

services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Camp
      - public-data:/Camp/public
      - tmp-data:/Camp/tmp
      - log-data:/Camp/log
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: containers/nginx
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes:
      - public-data:/Camp/public
      - tmp-data:/Camp/tmp
    ports:
      - 80:80
    depends_on:
      - app 
    tty: true
    stdin_open: true

volumes:
  db-volume:
  public-data:
  tmp-data:
  log-data:
  db-data: