default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: Camp_development

test:
  <<: *default
  database: Camp_test

production:
  <<: *default
  database: Camp_production
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  host: localhost